project:
  type: website
  output-dir: docs

website:
  title: "Alzheimer's Disease (AD) Versus Functional Assessment Score"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - p2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


