---
title: "Base Plot"
execute: 
  echo: false
---

Alzheimer's disease is ranked the 7th leading cause of death in the United States and affects more than 6 million Americans. The following data was sourced from a Kaggle dataset that focused on the broad topic of Alzheimer's disease. The variables used in these analyses were chosen to examine the association between Alzheimer's and physical functioning. The plots on the succeeding pages explore the validity of the "base plot" by acknowledging the potential confounding variables of age and gender. Overall there appears to be a strong association between and Alzheimer's and physical function. People with lower physical function had higher percentages of Alzheimer's disease.

```{r}
library(ggplot2)

data <- data.frame(
  FunctionalAssessment = c('0-1', '1-2', '2-3', '3-4', '4-5', '5-6', '6-7', '7-8', '8-9', '9-10'),
  Percent_AD = c(55.71, 58.33, 53.44, 57.11, 52.1, 18.69, 15.67, 14.16, 15.35, 16.1)
)

ggplot(data, aes(x = FunctionalAssessment, y = Percent_AD)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme_minimal() +
  labs(title = "Percent AD",
       x = "Functional Assessment Score",
       y = "Percentage with AD") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
    scale_y_continuous(limits = c(0, 100))

```






My email: jasonfisher2025@gmail.com

My GitHub repo for this project: <https://github.com/jasonfisher0/Data-Project>

Course homepage: <https://bootcamp.davidkane.info>